### ISSUE TITLE
Cannot install fletxible

### ISSUE THREAD

**Issue by pyracoon** [LineIndent/fletxible#1]
While writing pip install Fletxible it shows "ERROR: Failed building wheel for pickle5" if i try to install pickle5 it shows  "Failed building wheel for pickle5
  Running setup.py clean for pickle5
Failed to build pickle5
ERROR: Could not build wheels for pickle5, which is required to install pyproject.toml-based projects"
Need your help

**Comment by LineIndent** [comment]
Can you tell me what system you're installing the library on? 

Can you also make sure you have the newest version of ```pip``` installed.

**Comment by pyracoon** [comment]
My pip version is pip 23.1.2. Python version  is 3.9. I am using pycharm(latest version). Processor core i5. RAM 8 GB

**Comment by LineIndent** [comment]
I tested it out on my end and it works fine. It also works on Windows and Linux. 

What I suggest is to make sure you have installed the necessary build tools (you can find the command online corresponding to your OS).

But before that, try installing pickle5 separately and see if that works, if you haven't tried it yet. 

In the meantime, I'll see if I can update the package in any way.

**Comment by cfn96** [comment]
It seems there's a problem with pickle5 when I try to install it alone. I'm using the latest version of python(3.11.3)

**Comment by LineIndent** [comment]
So I tried to change the routes.pickle file that's generated when the library is installed. The problem is, and this is the way the script is set up, that the modules inside the routes.pickle file are stored as binary because as far as I know it's the only way a module can be stored. 

Now I'm trying to figure out another way to store the modules for now. 
I've updated the pickle5 library to v0.0.12. So try installing Fletxible v0.3.1 and see if that changes anything. 

Also make sure the library wheel is installed too: ```pip3 install wheel```.

**Comment by cfn96** [comment]
Thanks. I've installed wheel. I  am using pipenv as virtual environment
I tried `pipenv install fletxible`
Here's the output.

` Installing fletxible...
  Error:  An error occurred while installing fletxible!
  Error text: Collecting fletxible
    Downloading Fletxible-0.3.1-py3-none-any.whl (7.4 kB)
  Collecting click==8.1.3
    Using cached click-8.1.3-py3-none-any.whl (96 kB)
  Requirement already satisfied: flet==0.6.2 in /home/ceejaynudo/.local/share/virtualenvs/Flet-GZ1-1Dvh/lib64/python3.11/site-packages (from fletxible->-r /tmp/pipenv-m4eu_hf3-requirements/pipenv-zwbr6fs1-requirement.txt (line 1)) (0.6.2)
  Collecting fletxible
    Using cached Fletxible-0.3.0-py3-none-any.whl (6.8 kB)
  Collecting pickle5==0.0.11
    Using cached pickle5-0.0.11.tar.gz (132 kB)
    Preparing metadata (setup.py): started
    Preparing metadata (setup.py): finished with status 'done'
  Collecting PyYAML==6.0
    Using cached PyYAML-6.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (757 kB)
  Requirement already satisfied: flet-core==0.6.2 in /home/ceejaynudo/.local/share/virtualenvs/Flet-GZ1-1Dvh/lib64/python3.11/site-packages (from flet==0.6.2->fletxible->-r /tmp/pipenv-m4eu_hf3-requirements/pipenv-zwbr6fs1-requirement.txt (line 1)) (0.6.2)
  Requirement already satisfied: httpx<0.24.0,>=0.23.3 in /home/ceejaynudo/.local/share/virtualenvs/Flet-GZ1-1Dvh/lib64/python3.11/site-packages (from flet==0.6.2->fletxible->-r /tmp/pipenv-m4eu_hf3-requirements/pipenv-zwbr6fs1-requirement.txt (line 1)) (0.23.3)
  Requirement already satisfied: oauthlib<4.0.0,>=3.2.2 in /home/ceejaynudo/.local/share/virtualenvs/Flet-GZ1-1Dvh/lib64/python3.11/site-packages (from flet==0.6.2->fletxible->-r /tmp/pipenv-m4eu_hf3-requirements/pipenv-zwbr6fs1-requirement.txt (line 1)) (3.2.2)
  Requirement already satisfied: packaging<24.0,>=23.0 in /home/ceejaynudo/.local/share/virtualenvs/Flet-GZ1-1Dvh/lib64/python3.11/site-packages (from flet==0.6.2->fletxible->-r /tmp/pipenv-m4eu_hf3-requirements/pipenv-zwbr6fs1-requirement.txt (line 1)) (23.1)
  Requirement already satisfied: watchdog<3.0.0,>=2.2.1 in /home/ceejaynudo/.local/share/virtualenvs/Flet-GZ1-1Dvh/lib64/python3.11/site-packages (from flet==0.6.2->fletxible->-r /tmp/pipenv-m4eu_hf3-requirements/pipenv-zwbr6fs1-requirement.txt (line 1)) (2.3.1)
  Requirement already satisfied: websocket-client<2.0.0,>=1.4.2 in /home/ceejaynudo/.local/share/virtualenvs/Flet-GZ1-1Dvh/lib64/python3.11/site-packages (from flet==0.6.2->fletxible->-r /tmp/pipenv-m4eu_hf3-requirements/pipenv-zwbr6fs1-requirement.txt (line 1)) (1.5.1)
  Requirement already satisfied: websockets<11.0,>=10.4 in /home/ceejaynudo/.local/share/virtualenvs/Flet-GZ1-1Dvh/lib64/python3.11/site-packages (from flet==0.6.2->fletxible->-r /tmp/pipenv-m4eu_hf3-requirements/pipenv-zwbr6fs1-requirement.txt (line 1)) (10.4)
  Requirement already satisfied: repath<0.10.0,>=0.9.0 in /home/ceejaynudo/.local/share/virtualenvs/Flet-GZ1-1Dvh/lib64/python3.11/site-packages (from flet-core==0.6.2->flet==0.6.2->fletxible->-r /tmp/pipenv-m4eu_hf3-requirements/pipenv-zwbr6fs1-requirement.txt (line 1)) (0.9.0)
  Requirement already satisfied: certifi in /home/ceejaynudo/.local/share/virtualenvs/Flet-GZ1-1Dvh/lib64/python3.11/site-packages (from httpx<0.24.0,>=0.23.3->flet==0.6.2->fletxible->-r /tmp/pipenv-m4eu_hf3-requirements/pipenv-zwbr6fs1-requirement.txt (line 1)) (2023.5.7)
  Requirement already satisfied: httpcore<0.17.0,>=0.15.0 in /home/ceejaynudo/.local/share/virtualenvs/Flet-GZ1-1Dvh/lib64/python3.11/site-packages (from httpx<0.24.0,>=0.23.3->flet==0.6.2->fletxible->-r /tmp/pipenv-m4eu_hf3-requirements/pipenv-zwbr6fs1-requirement.txt (line 1)) (0.16.3)
  Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in /home/ceejaynudo/.local/share/virtualenvs/Flet-GZ1-1Dvh/lib64/python3.11/site-packages (from httpx<0.24.0,>=0.23.3->flet==0.6.2->fletxible->-r /tmp/pipenv-m4eu_hf3-requirements/pipenv-zwbr6fs1-requirement.txt (line 1)) (1.5.0)
  Requirement already satisfied: sniffio in /home/ceejaynudo/.local/share/virtualenvs/Flet-GZ1-1Dvh/lib64/python3.11/site-packages (from httpx<0.24.0,>=0.23.3->flet==0.6.2->fletxible->-r /tmp/pipenv-m4eu_hf3-requirements/pipenv-zwbr6fs1-requirement.txt (line 1)) (1.3.0)
  Requirement already satisfied: h11<0.15,>=0.13 in /home/ceejaynudo/.local/share/virtualenvs/Flet-GZ1-1Dvh/lib64/python3.11/site-packages (from httpcore<0.17.0,>=0.15.0->httpx<0.24.0,>=0.23.3->flet==0.6.2->fletxible->-r /tmp/pipenv-m4eu_hf3-requirements/pipenv-zwbr6fs1-requirement.txt (line 1)) (0.14.0)
  Requirement already satisfied: anyio<5.0,>=3.0 in /home/ceejaynudo/.local/share/virtualenvs/Flet-GZ1-1Dvh/lib64/python3.11/site-packages (from httpcore<0.17.0,>=0.15.0->httpx<0.24.0,>=0.23.3->flet==0.6.2->fletxible->-r /tmp/pipenv-m4eu_hf3-requirements/pipenv-zwbr6fs1-requirement.txt (line 1)) (3.6.2)
  Requirement already satisfied: six>=1.9.0 in /home/ceejaynudo/.local/share/virtualenvs/Flet-GZ1-1Dvh/lib64/python3.11/site-packages (from repath<0.10.0,>=0.9.0->flet-core==0.6.2->flet==0.6.2->fletxible->-r /tmp/pipenv-m4eu_hf3-requirements/pipenv-zwbr6fs1-requirement.txt (line 1)) (1.16.0)
  Requirement already satisfied: idna in /home/ceejaynudo/.local/share/virtualenvs/Flet-GZ1-1Dvh/lib64/python3.11/site-packages (from rfc3986[idna2008]<2,>=1.3->httpx<0.24.0,>=0.23.3->flet==0.6.2->fletxible->-r /tmp/pipenv-m4eu_hf3-requirements/pipenv-zwbr6fs1-requirement.txt (line 1)) (3.4)
  Building wheels for collected packages: pickle5
    Building wheel for pickle5 (setup.py): started
    Building wheel for pickle5 (setup.py): finished with status 'error'
    Running setup.py clean for pickle5
  Failed to build pickle5
  Installing collected packages: pickle5, PyYAML, click, fletxible
    Running setup.py install for pickle5: started
    Running setup.py install for pickle5: finished with status 'error'
  
    error: subprocess-exited-with-error
    
    × python setup.py bdist_wheel did not run successfully.
    │ exit code: 1
    ╰─> [22 lines of output]
        running bdist_wheel
        running build
        running build_py
        creating build
        creating build/lib.linux-x86_64-cpython-311
        creating build/lib.linux-x86_64-cpython-311/pickle5
        copying pickle5/pickletools.py -> build/lib.linux-x86_64-cpython-311/pickle5
        copying pickle5/pickle.py -> build/lib.linux-x86_64-cpython-311/pickle5
        copying pickle5/__init__.py -> build/lib.linux-x86_64-cpython-311/pickle5
        creating build/lib.linux-x86_64-cpython-311/pickle5/test
        copying pickle5/test/test_picklebuffer.py -> build/lib.linux-x86_64-cpython-311/pickle5/test
        copying pickle5/test/test_pickle.py -> build/lib.linux-x86_64-cpython-311/pickle5/test
        copying pickle5/test/pickletester.py -> build/lib.linux-x86_64-cpython-311/pickle5/test
        copying pickle5/test/__init__.py -> build/lib.linux-x86_64-cpython-311/pickle5/test
        warning: build_py: byte-compiling is disabled, skipping.
        
        running build_ext
        building 'pickle5._pickle' extension
        creating build/temp.linux-x86_64-cpython-311
        creating build/temp.linux-x86_64-cpython-311/pickle5
        gcc -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/home/ceejaynudo/.local/share/virtualenvs/Flet-GZ1-1Dvh/include -I/usr/include/python3.11 -c pickle5/_pickle.c -o build/temp.linux-x86_64-cpython-311/pickle5/_pickle.o -std=c99
        error: command 'gcc' failed: No such file or directory
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building wheel for pickle5
    error: subprocess-exited-with-error
    
    × Running setup.py install for pickle5 did not run successfully.
    │ exit code: 1
    ╰─> [24 lines of output]
        running install
        /home/ceejaynudo/.local/share/virtualenvs/Flet-GZ1-1Dvh/lib64/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        running build
        running build_py
        creating build
        creating build/lib.linux-x86_64-cpython-311
        creating build/lib.linux-x86_64-cpython-311/pickle5
        copying pickle5/pickletools.py -> build/lib.linux-x86_64-cpython-311/pickle5
        copying pickle5/pickle.py -> build/lib.linux-x86_64-cpython-311/pickle5
        copying pickle5/__init__.py -> build/lib.linux-x86_64-cpython-311/pickle5
        creating build/lib.linux-x86_64-cpython-311/pickle5/test
        copying pickle5/test/test_picklebuffer.py -> build/lib.linux-x86_64-cpython-311/pickle5/test
        copying pickle5/test/test_pickle.py -> build/lib.linux-x86_64-cpython-311/pickle5/test
        copying pickle5/test/pickletester.py -> build/lib.linux-x86_64-cpython-311/pickle5/test
        copying pickle5/test/__init__.py -> build/lib.linux-x86_64-cpython-311/pickle5/test
        warning: build_py: byte-compiling is disabled, skipping.
        
        running build_ext
        building 'pickle5._pickle' extension
        creating build/temp.linux-x86_64-cpython-311
        creating build/temp.linux-x86_64-cpython-311/pickle5
        gcc -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/home/ceejaynudo/.local/share/virtualenvs/Flet-GZ1-1Dvh/include -I/usr/include/python3.11 -c pickle5/_pickle.c -o build/temp.linux-x86_64-cpython-311/pickle5/_pickle.o -std=c99
        error: command 'gcc' failed: No such file or directory
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: legacy-install-failure
  
  × Encountered error while trying to install package.
  ╰─> pickle5
  
  note: This is an issue with the package mentioned above, not pip.
  hint: See above for output from the failure. `

**Comment by LineIndent** [comment]
Yeah so as the result says, the issue is with pickle and not the library itself. Perhaps there are some build tools missing from your system.

If you can't solve the issue maybe try a clean wipe and install your editor as well as your Python fresh. 

I'll keep searching for solutions in the meantime.

**Comment by cfn96** [comment]
Thanks. I think we need to wait for pickle5 update since it's the one causing problems upon installation of your repo. I also think new python version has to do with installing pickle5 concern.

**Comment by cfn96** [comment]
Thanks. I think we need to wait for pickle5 update since it's the one causing problems upon installation of your repo. I also think new python version has to do with installing pickle5 concern.

**Comment by BrownNPC** [comment]
Hi i'm having the same issue. If you don't mind me asking.. why are you using the pickle5 backport if you can just use python's own pickle module which was added in 3.8?

**Comment by cfn96** [comment]
I never thought python has its own pickle module since I'm still learning to code on python. I just tried doing what @LineIndent said here 

> But before that, try installing pickle5 separately and see if that works, if you haven't tried it yet.

my apologies :)

**Comment by LineIndent** [comment]
> Hi i'm having the same issue. If you don't mind me asking.. why are you using the pickle5 backport if you can just use python's own pickle module which was added in 3.8?

I wasn't aware Python had this built in. In that case I can probably remove the third party dependency and use the built in module. 
Thanks for pointing this out!

**Comment by LineIndent** [comment]
I have removed the third-party dependency ```pickle5``` from the package manager. I tested the library and it works. 
Hopefully this should clear any problems with loading the script and installing the other packages.

**Comment by wanghaisheng** [comment]
(base) wenke@wenkedeMac-mini flet-alchemy %  pip install Fletxible
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting Fletxible
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/48/33/610f021ed4d2ce9236f87795c82f9c369ecb10df5c9a0ccc25d99ec5f59c/Fletxible-0.3.1-py3-none-any.whl (7.4 kB)
ERROR: Could not find a version that satisfies the requirement pickle5==0.0.12 (from Fletxible) (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11)
ERROR: No matching distribution found for pickle5==0.0.12 (from Fletxible)

**Comment by LineIndent** [comment]
> (base) wenke@wenkedeMac-mini flet-alchemy %  pip install Fletxible
> 
> Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
> 
> Collecting Fletxible
> 
>   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/48/33/610f021ed4d2ce9236f87795c82f9c369ecb10df5c9a0ccc25d99ec5f59c/Fletxible-0.3.1-py3-none-any.whl (7.4 kB)
> 
> ERROR: Could not find a version that satisfies the requirement pickle5==0.0.12 (from Fletxible) (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11)
> 
> ERROR: No matching distribution found for pickle5==0.0.12 (from Fletxible)

Can you try and install the package now. The library has been updated.

**Comment by wanghaisheng** [comment]
yes 
I change to another mirror and there it is
